version: 2
updates:
  # Ignore all files in the attic directory for the node ecosystem
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "attic/**"

  # Ignore all files in the attic directory for the .NET ecosystem (nuget)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "attic/**"
